class Freefem < Formula
  desc "Finite element method PDE solver"
  homepage "https://freefem.org"
  url "https://github.com/FreeFem/FreeFem-sources/archive/refs/tags/v4.17.tar.gz"
  sha256 "b1198448c0394d42d8371e398aee209a92a50067082d866cdf5f11f56a636835"
  license "LGPL-3.0-only"

  # Populated by .github/workflows/bottle.yml (manual dispatch) -- it
  # builds+tests+bottles on GitHub-hosted macOS runners, uploads the
  # tarballs to this repo's "bottles" GitHub Release (assets get
  # overwritten in place on every run, so this one release/root_url
  # never needs to change across version or rebuild bumps), and pushes
  # the resulting sha256 lines back here via `brew bottle --merge
  # --write`. No sha256 lines yet -- CI hasn't run since this tap started
  # publishing bottles that way; until it does (or on any machine/OS
  # combination it doesn't cover), `brew install` transparently falls
  # back to building from source.
  bottle do
    root_url "https://github.com/olivierpironneau/homebrew-freefem/releases/download/bottles"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "cmake" => :build
  depends_on "fftw"
  depends_on "gcc" # libgfortran, libquadmath
  depends_on "gsl"
  depends_on "hdf5"
  depends_on "hwloc"
  depends_on "libevent"
  depends_on "open-mpi"
  depends_on "pmix"

  # PETSc/SLEPc get built from source below (cd 3rdparty/ff-petsc && make
  # petsc-slepc, a genuine ~30-45 minute build with its own large
  # dependency stack: METIS/ParMETIS/PTScotch/HYPRE/SuperLU/SuiteSparse/
  # GSL/mmg/parmmg/ScaLAPACK/MUMPS). An earlier version of this formula
  # tried reusing an already-built PETSc from a native (non-Homebrew)
  # build done weeks earlier, to skip that wait -- it built and even
  # bottled fine, but PetscInitialize segfaulted at runtime inside
  # MPI_Comm_set_errhandler (confirmed via a plain, non-PETSc MPI test
  # working perfectly on the exact same install, isolating the crash to
  # PETSc specifically). Root cause: Homebrew's open-mpi had been
  # upgraded since that PETSc was built, and PETSc's own ./configure
  # detects and bakes in MPI ABI/struct-layout details at ITS build time
  # that a dylib-reference rewrite can't retroactively fix across an MPI
  # version bump. Building fresh, against whatever open-mpi is actually
  # installed right now, is the only reliable fix.

  def install
    # Homebrew's gcc formula only symlinks unversioned `gfortran` (no Apple
    # equivalent to clash with) -- `gcc`/`g++` stay versioned (gcc-16,
    # g++-16, ...) to avoid shadowing Apple's /usr/bin/gcc shim. Resolve
    # the actual versioned names rather than hardcoding a version that
    # will go stale on the next gcc bump.
    gfortran   = formula_opt_bin("gcc")/"gfortran"
    gcc_ver    = Formula["gcc"].version.major
    gcc        = formula_opt_bin("gcc")/"gcc-#{gcc_ver}"
    gxx        = formula_opt_bin("gcc")/"g++-#{gcc_ver}"
    gcclib     = formula_opt_lib("gcc")/"gcc/current"

    # v4.17's release tarball, unlike v4.16's, does NOT bundle the
    # downloaded 3rdparty sources -- only the Makefiles/patches that fetch
    # them via `--enable-download`. That's fine for most packages (they
    # download+configure+build fine from scratch inside Homebrew's
    # sandbox, same as any other --enable-download build, and PETSc's own
    # --download-* flags below prove outbound network access during
    # `install` works fine in this sandbox). SuperLU, ScaLAPACK and Scotch
    # are the exceptions: the source patches further below need their
    # sources to already exist on disk, and FreeFEM's own
    # 3rdparty/{superlu,scalapack,scotch}/Makefile already know how to
    # fetch+extract each one (via 3rdparty/getall) with no compiling --
    # `make superlu-sources` / `make scalapack-2.1.0/tag-tar` / `make
    # scotch-v6.1.0` do exactly that, so use them directly instead of a
    # hand-rolled download or a pre-staged local copy that would only
    # ever exist on one machine.
    #
    # All three of those targets sit behind an `include` of a file
    # (ff-FLAGS / SLmake.inc / Makefile.inc) generated from THIS build's
    # own top-level Makefile or ./configure output -- GNU Make resolves
    # `include` before it'll run ANY target in that Makefile, even one
    # (like these) that doesn't actually need what's included. So none of
    # the three can run until AFTER a ./configure call; see below.
    system "tar", "zxf", "AutoGeneratedFile.tar.gz"

    # `make install` unconditionally tries to install the legacy
    # FreeFem++-CoCoa AppleScript droplet into the SYSTEM /usr/local/bin
    # (root-owned, not writable by a normal build). The recipe's leading
    # "-" only tells make to ignore a FAILED exit code from that line --
    # it still has to wait for the command to actually finish first, and
    # on this machine (macOS 27 beta) that `rm`/`install` against
    # /usr/local/bin doesn't fail fast, it just hangs indefinitely
    # (confirmed: stuck at 0% CPU for 15+ minutes). We don't need this
    # binary at all -- it's superseded by this formula's own
    # FreeFem++.app bundling further down -- so neutralize the recipe
    # line rather than work around the hang.
    #
    # Patch Makefile.in (from AutoGeneratedFile.tar.gz), NOT Makefile.am:
    # regenerating Makefile.in from a patched Makefile.am needs the full
    # aclocal/autoconf/automake context (AM_INIT_AUTOMAKE, aclocal.m4,
    # ChangeLog.md/INSTALL/NEWS/COPYING, AM_CONDITIONAL vars for
    # subdir-objects/depend2.am, ...) that a bare `automake` invocation in
    # this extracted-tarball tree doesn't have -- confirmed, it fails hard
    # with "no proper invocation of AM_INIT_AUTOMAKE was found" and half a
    # dozen other errors. Makefile.in is already the FULLY-EXPANDED,
    # pre-generated file upstream ships (config.status turns it straight
    # into Makefile, no automake involved at build time), so patching it
    # directly sidesteps all of that.
    inreplace "Makefile.in",
      '-test `uname` != Darwin || ( rm "$(DESTDIR)/usr/local/bin/FreeFem++-CoCoa"; $(INSTALL_SCRIPT) FreeFem++-CoCoa "$(DESTDIR)/usr/local/bin" )',
      "\t@true # (removed: legacy /usr/local/bin install, hangs on this OS -- see freefem.rb)"
    inreplace "Makefile.in",
      'test `uname` != Darwin || $(INSTALL_SCRIPT) FreeFem++-CoCoa "$(DESTDIR)${bindir}"',
      "\t@true # (removed: legacy CoCoa droplet install -- see freefem.rb)"
    # Belt-and-suspenders against --enable-maintainer-mode's auto-remake
    # rule deciding Makefile.in is stale (relative to Makefile.am/
    # configure.ac) and trying to regenerate it via automake mid-build --
    # which would hit the exact same missing-context failure and/or
    # silently discard this patch. inreplace above already bumps
    # Makefile.in's mtime as a side effect of writing it; touch configure
    # and config.h.in too so the whole AutoGeneratedFile.tar.gz set reads
    # as newer than anything from the outer release tarball.
    system "touch", "Makefile.in", "configure", "config.h.in"

    ENV["CC"]     = gcc.to_s
    ENV["CXX"]    = gxx.to_s
    ENV["FC"]     = gfortran.to_s
    ENV["F77"]    = gfortran.to_s
    ENV["CFLAGS"] = "-std=gnu11 #{ENV["CFLAGS"]}"

    # Open MPI's own mpicc/mpicxx/mpif90 wrapper compilers default to
    # whatever compiler open-mpi ITSELF was built with (clang, Homebrew's
    # default), regardless of the CC/CXX/FC set above -- confirmed:
    # FreeFem++/FreeFem++-nw (plain g++-16 link) built fine, but
    # FreeFem++-mpi failed with missing C++ stdlib symbols (vtables,
    # operator<<, ...), the classic signature of linking g++-16-compiled
    # objects through clang's libc++ ABI instead of libstdc++. OMPI_CXX/
    # OMPI_CC/OMPI_FC are Open MPI's own documented override variables for
    # exactly this: pin the wrappers to the same compilers as everything
    # else.
    ENV["OMPI_CC"]  = gcc.to_s
    ENV["OMPI_CXX"] = gxx.to_s
    ENV["OMPI_FC"]  = gfortran.to_s

    # ── Source patches ─────────────────────────────────────────────
    # Scotch: force -std=gnu11 (GCC 16 defaults to C23, which breaks Scotch's function-pointer tables)
    # This one patches a template file that ships in the release tarball
    # itself (no extraction needed), so -- unlike SuperLU/ScaLAPACK below
    # -- it's safe to apply before any ./configure call.
    inreplace "3rdparty/scotch/Makefile-scotch.inc" do |s|
      s.gsub!(/^CCS\s*=.*$/, "CCS = #{gcc} -std=gnu11")
      s.gsub!(/^CCD\s*=.*$/, "CCD = #{gcc} -std=gnu11")
    end

    # ── PETSc/SLEPc: build from source, against THIS toolchain ───────
    # 3rdparty/ff-petsc/Makefile needs FreeFEM's OUTER ./configure to have
    # already run once (it reads FF_prefix_petsc, compiler paths, etc.
    # from the Makefile.inc that generates) -- a throwaway, PETSc-less
    # configure pass first, same ordering already established for the
    # CoCoa/Makefile.in patch above.
    system "./configure",
      "--prefix=#{prefix}",
      "--enable-download",
      "--enable-optim",
      "--enable-m64",
      "--enable-maintainer-mode",
      "F77=#{gfortran}",
      "FC=#{gfortran}"

    # SuperLU's and ScaLAPACK's own extraction targets both sit behind an
    # `include` (ff-FLAGS / SLmake.inc) generated from THIS build's own
    # top-level Makefile / ./configure output, so neither could run until
    # now -- the throwaway pass just above has produced both. Both
    # targets only download+extract (no compiling).
    cd "3rdparty/superlu" do
      system "make", "superlu-sources"
    end

    superlu = "3rdparty/superlu/superlu-sources/SRC"

    # SuperLU: fix empty () forward declarations (errors in Clang 21 / GCC 16 -std=gnu23)
    inreplace "#{superlu}/sgstrs.c",      "void sprint_soln();",         "void sprint_soln(int, int, float *);"
    inreplace "#{superlu}/dgstrs.c",      "void dprint_soln();",         "void dprint_soln(int, int, double *);"
    inreplace "#{superlu}/cgstrs.c",      "void cprint_soln();",         "void cprint_soln(int, int, complex *);"
    inreplace "#{superlu}/zgstrs.c",      "void zprint_soln();",         "void zprint_soln(int, int, doublecomplex *);"
    inreplace "#{superlu}/spanel_bmod.c", "extern void scheck_tempv();", "extern void scheck_tempv(int, float *);"
    inreplace "#{superlu}/cpanel_bmod.c", "extern void ccheck_tempv();", "extern void ccheck_tempv(int, complex *);"
    inreplace "#{superlu}/dpanel_bmod.c", "extern void dcheck_tempv();", "extern void dcheck_tempv(int, double *);"
    inreplace "#{superlu}/zpanel_bmod.c", "extern void zcheck_tempv();", "extern void zcheck_tempv(int, doublecomplex *);"

    %w[s d c z].each do |p|
      path_triple = "#{superlu}/#{p}readtriple.c"
      path_mm     = "#{superlu}/#{p}readMM.c"
      inreplace path_triple, "FILE *fp, *fopen();", "FILE *fp;" if File.exist?(path_triple)
      inreplace path_mm,     "FILE *fp, *fopen();", "FILE *fp;" if File.exist?(path_mm)
    end

    # SuperLU *myblas2.c: convert K&R-style function definitions to ANSI C
    {
      "smyblas2.c" => { type: "float",         matvec: "float *M, float *vec, float *Mxvec" },
      "dmyblas2.c" => { type: "double",        matvec: "double *M, double *vec, double *Mxvec" },
      "cmyblas2.c" => { type: "complex",       matvec: "complex *M, complex *vec, complex *Mxvec" },
      "zmyblas2.c" => { type: "doublecomplex", matvec: "doublecomplex *M, doublecomplex *vec, doublecomplex *Mxvec" },
    }.each do |fname, info|
      path = "#{superlu}/#{fname}"
      pfx  = fname[0]
      t    = info[:type]
      content = File.read(path)
      content.gsub!(
        /void\s*\n#{pfx}usolve\s*\([^)]*\)\s*\nint ldm;.*?int ncol;.*?#{t} \*M;.*?#{t} \*rhs;\s*\n/m,
        "void\n#{pfx}usolve (int ldm, int ncol, #{t} *M, #{t} *rhs)\n",
      )
      content.gsub!(
        /void #{pfx}matvec\s*\([^)]*\)\s*\n+int ldm;.*?int nrow;.*?int ncol;.*?#{t} \*M;.*?#{t} \*vec;.*?#{t} \*Mxvec;\s*\n/m,
        "void #{pfx}matvec (int ldm, int nrow, int ncol, #{info[:matvec]})\n",
      )
      File.write(path, content)
    end

    cd "3rdparty/scalapack" do
      system "make", "scalapack-2.1.0/tag-tar"
    end

    # ScaLAPACK: K&R missing type for gcontext parameter
    inreplace "3rdparty/scalapack/scalapack-2.1.0/REDIST/SRC/pgemraux.c",
      "  int   i, j, m, n, p, q;",
      "  int   i, j, m, n, p, q, gcontext;"

    # PETSc downloads and builds its OWN copies of METIS/ParMETIS/
    # PTScotch/HYPRE/SuperLU/SuiteSparse/ScaLAPACK/MUMPS independently
    # (via its own --download-* configure flags) -- several of those are
    # old K&R-style C that recent compilers reject outright by default
    # (already needed for FreeFEM's own superlu/scalapack above); apply
    # the same suppression here so PETSc's sub-builds don't hit it too.
    ENV["CC"] = "#{gcc} -Wno-implicit-int -Wno-implicit-function-declaration"

    cd "3rdparty/ff-petsc" do
      system "make", "petsc-slepc"
    end

    petsc_dir     = prefix/"ff-petsc"
    petsc_real    = petsc_dir/"r/lib/petsc/conf/petscvariables"
    petsc_complex = petsc_dir/"c/lib/petsc/conf/petscvariables"
    odie "PETSc build did not produce petscvariables" unless petsc_real.exist? && petsc_complex.exist?

    # ── Configure (real, PETSc-aware pass) ──────────────────────────
    system "./configure",
      "--prefix=#{prefix}",
      "--enable-download",
      "--enable-optim",
      "--enable-m64",
      "--enable-maintainer-mode",
      "--with-petsc=#{petsc_real}",
      "--with-petsc_complex=#{petsc_complex}",
      "F77=#{gfortran}",
      "FC=#{gfortran}"

    cd "3rdparty/scotch" do
      # Same `include Makefile.inc` / config.status dependency as
      # ScaLAPACK above -- config.status exists by now (second configure
      # just ran), so `make scotch-v6.1.0` (download+extract only, no
      # compiling) is safe here.
      system "make", "scotch-v6.1.0"
      system "../../config.status", "--file=Makefile.inc:Makefile-scotch.inc"
      cp "Makefile.inc", "scotch-v6.1.0/src/"
    end

    system "make", "-j#{ENV.make_jobs}"
    system "make", "install"

    # FreeFem++-CoCoa: a plain droplet shell script (generated from
    # bin/FreeFem++-CoCoa.in by config.status during the ./configure
    # passes above, already substituted with THIS build's real prefix/
    # bindir) -- drop .edp files onto it (or the .app built below) to run
    # them. Its own `make install` recipe line was neutralized above
    # because the recipe line right before it (installing a second copy
    # into the SYSTEM /usr/local/bin) hangs on this OS; install this one
    # directly instead of trying to selectively un-neutralize the recipe.
    bin.install "FreeFem++-CoCoa"

    # ── Bundle gfortran runtime ────────────────────────────────────
    gnudir = prefix/"gnu"
    gnudir.mkpath

    # libstdc++ rides along with libgfortran/libquadmath/libgcc_s here too:
    # PETSc's own build (SuiteSparse/ScaLAPACK/mmg/hpddm, all compiled via
    # mpicc/g++) links it in directly, and if it isn't bundled+rewritten
    # the same way, those libs keep an absolute reference straight to
    # Homebrew's live gcc install -- confirmed root cause of a real crash:
    # dyld ends up loading gnudir's libstdc++ AND the live Homebrew one as
    # two separate images sharing one UUID, each running its own static
    # initializer (std::ios_base::Init) -> abort.
    gfortran_libs = %w[libgfortran.5.dylib libquadmath.0.dylib libgcc_s.1.1.dylib libstdc++.6.dylib]
    gfortran_libs.each { |lib| cp gcclib/lib, gnudir }
    (gnudir/"libgfortran.dylib").make_symlink "libgfortran.5.dylib"
    (gnudir/"libquadmath.dylib").make_symlink "libquadmath.0.dylib"

    [gnudir/"libgfortran.5.dylib", gnudir/"libquadmath.0.dylib", gnudir/"libgcc_s.1.1.dylib", gnudir/"libstdc++.6.dylib"].each do |f|
      chmod 0644, f
      MachO::Tools.change_dylib_id(f.to_s, "@rpath/#{f.basename}")
      gfortran_libs.each do |dep|
        old = (gcclib/dep).to_s
        begin
          MachO::Tools.change_install_name(f.to_s, old, "@rpath/#{dep}")
        rescue MachO::MachOError
          nil
        end
      end
      system "codesign", "--remove-signature", f.to_s
      system "codesign", "-s", "-", f.to_s
    end

    # NOTE: rewriting every OTHER file's references to these gfortran/
    # libstdc++ libs (bin/*, lib/**, extlib/*, and everything PETSc built
    # for itself under ff-petsc/{r,c}/lib) happens in the generic closure
    # walker below -- `copied` gets seeded with these libs up front so
    # every consumer, wherever it lives, gets rewritten uniformly instead
    # of relying on a second, narrower pass that misses extlib/ff-petsc.

    # ── Bundle the rest of the external dependency closure ──────────
    # open-mpi/pmix/hwloc/libevent (MPI runtime), hdf5/gsl and everything
    # THEY pull in (aec, sz, ...), and PETSc's own huge dependency stack
    # (scalapack, mumps-related libs, suitesparse, metis/parmetis, hypre,
    # ptscotch, superlu, mmg/parmmg, ...) all get discovered transitively
    # here and copied into extlib/, so none of those Homebrew formulas are
    # needed at runtime. libpetsc*/libslepc* are the one exception: the
    # real (r/) and complex (c/) PETSc builds produce SAME-NAMED but
    # DIFFERENT-CONTENT files, so those two stay where they already are
    # (under ff-petsc/{r,c}/lib) and get an rpath to that directory instead
    # of being flattened into the shared extlib/.
    extlib = prefix/"extlib"
    extlib.mkpath
    system_prefixes = %w[/usr/lib/ /System/ /Library/Frameworks/]

    macho_p = lambda do |path|
      !File.symlink?(path) && File.file?(path) && `file -b #{path.shellescape}`.include?("Mach-O")
    end
    raw_deps = lambda do |path|
      `otool -L #{path.shellescape}`.lines.drop(1).filter_map { |l| l.strip.split(" (").first }
    end
    realpath_or_nil = lambda do |path|
      File.realpath(path)
    rescue StandardError
      nil
    end
    rpaths_of = lambda do |path|
      lines = `otool -l #{path.shellescape}`.lines
      paths = []
      lines.each_with_index do |line, i|
        next unless line.include?("cmd LC_RPATH")

        (i...[i + 4, lines.length].min).each do |j|
          next unless lines[j].include?("path ")

          paths << lines[j].strip.split("path ", 2).last.split(" (offset").first
          break
        end
      end
      paths
    end
    # Resolve a raw LC_LOAD_DYLIB string (absolute, or @rpath/@loader_path/
    # @executable_path-relative) referenced BY `referencing_file` to a real
    # absolute path, using referencing_file's OWN (not-yet-rewritten)
    # rpath commands for the relative forms. Needed because Homebrew
    # formulas commonly reference a sibling lib via a short SONAME symlink
    # (confirmed: hdf5's libhdf5_hl -> @rpath/libhdf5.320.dylib, a symlink
    # to the real libhdf5.320.2.0.dylib) -- looking such a dependency up
    # by its raw string alone won't match `copied`, which is keyed by the
    # realpath'd (symlink-resolved) target.
    resolve_dep = lambda do |referencing_file, dep|
      if dep.start_with?("/")
        next realpath_or_nil.call(dep)
      end

      own_dir = File.dirname(referencing_file)
      candidates = []
      if dep.start_with?("@rpath/")
        rest = dep.sub("@rpath/", "")
        rpaths_of.call(referencing_file).each do |rp|
          rp = rp.gsub("@loader_path", own_dir).gsub("@executable_path", own_dir)
          candidates << File.join(rp, rest)
        end
      elsif dep.start_with?("@loader_path/")
        candidates << File.join(own_dir, dep.sub("@loader_path/", ""))
      elsif dep.start_with?("@executable_path/")
        candidates << File.join(own_dir, dep.sub("@executable_path/", ""))
      else
        next nil
      end
      candidates.each do |c|
        rc = realpath_or_nil.call(c)
        next rc if rc && File.file?(rc)
      end
      nil
    end

    primary_files = (Dir["#{bin}/*"] + Dir["#{lib}/**/*.dylib"] + Dir["#{lib}/**/*.so"]).select { |f| macho_p.call(f) }
    # Plugin .dylibs install read-only (mode 555); this pass rewrites
    # install names on some of these too (see gfortran-bundling loop
    # above for the same issue/fix).
    primary_files.each { |f| chmod "u+w", f }

    # realpath -> { rpath_ref: "@rpath/x.dylib" } for a normal bundled lib,
    # or -> { rpath_dir: "<dir it's already in>" } for libpetsc*/libslepc*.
    copied = {}
    # Seed with libgfortran/libquadmath/libgcc_s/libstdc++'s REAL (symlink-
    # resolved) Homebrew paths -> the one bundled gnudir/ copy, so every
    # reference to them anywhere in the closure below resolves there
    # instead of re-copying them (they're already handled above) or,
    # worse, silently being left pointing at the live Homebrew install.
    gfortran_libs.each do |glib|
      real = realpath_or_nil.call((gcclib/glib).to_s)
      copied[real] = { rpath_dir: gnudir.to_s } if real
    end

    queue = primary_files.dup
    seen = []

    until queue.empty?
      f = queue.shift
      raw_deps.call(f).each do |dep|
        next if system_prefixes.any? { |p| dep.start_with?(p) }

        real = resolve_dep.call(f, dep)
        next unless real
        next if copied.key?(real)

        bn = File.basename(real)
        if real.start_with?("#{petsc_dir}/")
          copied[real] = { rpath_dir: File.dirname(real) }
        else
          next if real.start_with?("#{prefix}/") && !real.start_with?("#{petsc_dir}/") # our own install output, not an external dep

          target = extlib/bn
          unless target.exist?
            cp real, target
            # `cp` preserves source permissions -- some formulas (hdf5
            # confirmed) install their dylibs read-only, which then
            # blocks the install-name rewrite below.
            chmod "u+w", target
            # install_name_tool, not MachO::Tools.change_dylib_id: a file
            # ruby-macho has written to apparently isn't always laid out
            # the way Apple's OWN install_name_tool expects for a LATER
            # edit -- confirmed via CI (never reproduced locally): every
            # single file that hit "fatal error: file not in an order
            # that can be processed (link edit information does not fill
            # the __LINKEDIT segment)" on Xcode 15.4/16.4, across two
            # separate runs, was an extlib/ copy that got its ID set via
            # MachO::Tools here and was THEN edited again by
            # install_name_tool in the rewrite loop below -- petsc_self_
            # files and primary_files, never touched by MachO::Tools at
            # all, never hit it. Keeping the whole edit pipeline in
            # Apple's own tool avoids the cross-tool interop risk
            # entirely, whatever its exact cause.
            system "install_name_tool", "-id", "@rpath/#{bn}", target.to_s
            system "codesign", "--remove-signature", target.to_s
          end
          copied[real] = { rpath_ref: "@rpath/#{bn}" }
        end

        unless seen.include?(real)
          seen << real
          queue << real
        end
      end
    end

    # libpetsc*/libslepc* themselves (left in place under ff-petsc/{r,c}/lib,
    # see above) still need THEIR OWN cross-references to everything just
    # bundled into extlib/ rewritten too -- otherwise they're only correct
    # by virtue of Homebrew's own bottle-relocation pass, which is real but
    # not something to rely on exclusively here.
    petsc_self_files = Dir["#{petsc_dir}/{r,c}/lib/**/*"].select { |f| macho_p.call(f) }

    (primary_files + Dir[extlib/"*.dylib"] + petsc_self_files).uniq.each do |f|
      next unless macho_p.call(f)

      rpaths_to_add = []
      change_args = []
      raw_deps.call(f).each do |dep|
        real = resolve_dep.call(f, dep)
        if real.nil? && dep.start_with?("@rpath/")
          # resolve_dep needs a matching rpath ON THE REFERENCING FILE
          # ITSELF to work, and some formulas' internal sibling references
          # (confirmed: hdf5's libhdf5_hl -> @rpath/libhdf5.320.dylib) have
          # no such rpath at all -- yet the REAL target (libhdf5.320.2.0.
          # dylib) is often already in `copied` anyway, discovered via a
          # DIFFERENT file's absolute (already realpath'd-by-the-linker)
          # reference to the same library. Fall back to a SONAME-prefix
          # match against everything already bundled: @rpath/libX.MM.dylib
          # matches any copied libX.MM.*.dylib.
          soname_prefix = dep.sub("@rpath/", "").sub(/\.dylib\z/, ".")
          real = copied.keys.find { |r| File.basename(r).start_with?(soname_prefix) }
        end
        next unless real && copied.key?(real)

        info = copied[real]
        new_ref = info[:rpath_ref] || "@rpath/#{File.basename(real)}"
        change_args.concat(["-change", dep, new_ref]) if dep != new_ref
        rpaths_to_add << (info[:rpath_ref] ? extlib.to_s : info[:rpath_dir])
      end

      next if rpaths_to_add.empty?

      # Strip any EXISTING rpath that isn't one of ours before adding the
      # ones we actually need. Confirmed root cause of a real crash: PETSc's
      # own build (via mpicc) bakes in an rpath straight to Homebrew's
      # open-mpi (/opt/homebrew/opt/open-mpi/lib), listed BEFORE the extlib
      # rpath we add -- dyld resolves @rpath/libmpi.40.dylib through
      # rpaths IN ORDER, so libpetsc.dylib ended up loading the ORIGINAL
      # open-mpi copy while FreeFem++-mpi itself loaded the bundled extlib
      # copy: two byte-identical but SEPARATE dylib images in one process,
      # each with its own independent MPI global state, so PetscInitialize
      # called MPI_Comm_set_errhandler against a comm handle that was
      # meaningless in ITS copy's state -> segfault. Only a handful of
      # rpaths are ever intentionally ours; drop everything else.
      our_rpaths = [extlib.to_s, gnudir.to_s, (petsc_dir/"r/lib").to_s, (petsc_dir/"c/lib").to_s]
      existing_rpaths = rpaths_of.call(f)
      delete_args = existing_rpaths.reject { |rp| our_rpaths.include?(rp) }.flat_map { |rp| ["-delete_rpath", rp] }
      # Some files (confirmed: FreeFem++/FreeFem++-mpi, which already
      # link against ff-petsc/r/lib via -Wl,-rpath at compile time) come
      # in with one of our rpaths ALREADY present -- install_name_tool
      # refuses to -add_rpath a duplicate ("would duplicate path"), so
      # only add the ones genuinely missing. (Previously masked: the old
      # one-flag-per-call form silently swallowed this exact error via a
      # blanket rescue around each -add_rpath call.)
      add_args = (rpaths_to_add.uniq - existing_rpaths).flat_map { |rp| ["-add_rpath", rp] }
      all_args = change_args + delete_args + add_args

      # One install_name_tool invocation per EDIT (as this used to do --
      # a separate call per -change/-delete_rpath/-add_rpath) corrupts
      # some files' __LINKEDIT segment on certain Xcode toolchains --
      # confirmed via CI: "file not in an order that can be processed
      # (link edit information does not fill the __LINKEDIT segment)" on
      # BOTH Xcode 15.4 and 16.4, never reproduced locally against a
      # newer Xcode-beta toolchain that happens to tolerate it. Batch
      # every edit for a given file into the ONE call install_name_tool
      # itself is designed for (its own docs show -change/-delete_rpath/
      # -add_rpath combined in a single invocation) instead.
      system "install_name_tool", *all_args, f unless all_args.empty?

      system "codesign", "--remove-signature", f
      system "codesign", "-s", "-", f
    end

    # ── macOS app bundle ───────────────────────────────────────────
    # FreeFem++.app.tgz is a Makefile target (etc/config/FreeFem++.app.in.tgz
    # -> FreeFem++.app.tgz via config.status), not a file that ships
    # pre-built or gets produced as a side effect of `make install` -- the
    # Makefile.am recipe that would have built it automatically is
    # commented out upstream. Build it explicitly before extracting.
    system "make", "FreeFem++.app.tgz"
    # Extract the upstream scaffold (icons, AppleScript resources)
    system "tar", "zxf", "FreeFem++.app.tgz", "-C", prefix.to_s

    app = prefix/"FreeFem++.app"

    # Replace the x86-only AppletStub binary with a native shell script launcher
    (app/"Contents/MacOS/droplet").unlink
    (app/"Contents/MacOS/droplet").write <<~SH
      #!/bin/bash
      ff="#{opt_bin}/FreeFem++"
      cmd=""
      for f in "$@"; do
        dir=$(dirname "$f")
        base=$(basename "$f")
        cmd="${cmd}cd $(printf '%q' "$dir"); $ff $(printf '%q' "$base"); "
      done
      [ -z "$cmd" ] && cmd="$ff; "
      osascript <<OSASCRIPT
      tell application "Terminal"
        activate
        do script "${cmd}exit"
      end tell
      OSASCRIPT
    SH
    chmod "+x", app/"Contents/MacOS/droplet"

    # Update Info.plist: remove deprecated keys, set correct bundle metadata
    (app/"Contents/Info.plist").atomic_write <<~PLIST
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>CFBundleAllowMixedLocalizations</key><true/>
        <key>CFBundleDevelopmentRegion</key><string>en</string>
        <key>CFBundleDocumentTypes</key>
        <array>
          <dict>
            <key>CFBundleTypeExtensions</key><array><string>edp</string></array>
            <key>CFBundleTypeName</key><string>FreeFEM Script</string>
            <key>CFBundleTypeRole</key><string>Editor</string>
          </dict>
        </array>
        <key>CFBundleExecutable</key><string>droplet</string>
        <key>CFBundleIconFile</key><string>FreeFem++</string>
        <key>CFBundleIdentifier</key><string>org.freefem.FreeFem</string>
        <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
        <key>CFBundleName</key><string>FreeFem++</string>
        <key>CFBundleDisplayName</key><string>FreeFem++</string>
        <key>CFBundlePackageType</key><string>APPL</string>
        <key>CFBundleShortVersionString</key><string>#{version}</string>
        <key>CFBundleVersion</key><string>#{version}</string>
        <key>LSMinimumSystemVersion</key><string>12.0</string>
      </dict>
      </plist>
    PLIST

    # Write the app installer helper script
    (bin/"freefem-install-app").write <<~SH
      #!/bin/bash
      # Installs FreeFem++.app into /Applications (or a custom destination).
      # Usage: freefem-install-app [destination]   default: /Applications
      set -e
      SELF="$(python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0")"
      PREFIX="$(dirname "$(dirname "$SELF")")"
      APP="$PREFIX/FreeFem++.app"
      [ -d "$APP" ] || { echo "Error: FreeFem++.app not found at $APP" >&2; exit 1; }
      DEST="${1:-/Applications}"
      mkdir -p "$DEST"
      rm -rf "$DEST/FreeFem++.app"
      cp -r "$APP" "$DEST/"
      chmod -R a+rX "$DEST/FreeFem++.app"
      echo "FreeFem++.app installed in $DEST"
      echo "You can now drag .edp files onto it to run FreeFEM++."
    SH
    chmod "+x", bin/"freefem-install-app"
  end

  def caveats
    <<~EOS
      FreeFEM++ #{version} has been installed (with MPI and PETSc/SLEPc).

      CLI usage:
        FreeFem++ script.edp
        FreeFem++-mpi -np 4 script.edp

      To install FreeFem++.app so you can drag .edp files onto it, run:
        freefem-install-app            # installs to /Applications (system-wide)
        freefem-install-app ~/Applications  # current user only

      Plugins:
        #{opt_prefix}/lib/ff++/#{version}/lib/
      Gfortran runtime:
        #{opt_prefix}/gnu/
      PETSc/SLEPc (real + complex):
        #{opt_prefix}/ff-petsc/{r,c}/
    EOS
  end

  test do
    (testpath/"laplace.edp").write <<~EDP
      load "medit"
      mesh Th = square(10, 10);
      fespace Vh(Th, P1);
      Vh u, v;
      problem Laplace(u, v) =
        int2d(Th)(dx(u)*dx(v) + dy(u)*dy(v))
        - int2d(Th)(1*v)
        + on(1,2,3,4, u=0);
      Laplace;
      cout << "u max = " << u[].max << endl;
    EDP
    system bin/"FreeFem++", "-nw", "laplace.edp"

    # PETSc/MPI test: run one of FreeFEM's own shipped hpddm examples via
    # ff-mpirun -np 2, the same invocation already verified to work
    # end-to-end (real parallel solve, no dyld/library errors) against
    # this exact PETSc build outside Homebrew.
    petsc_example = share/"FreeFEM/#{version}/examples/hpddm/diffusion-2d-PETSc.edp"
    assert_path_exists petsc_example
    system bin/"ff-mpirun", "-np", "2", petsc_example, "-nw"
  end
end
