class Freefem < Formula
  desc "Finite element method PDE solver"
  homepage "https://freefem.org"
  url "https://github.com/FreeFem/FreeFem-sources/archive/refs/tags/v4.16.tar.gz"
  sha256 "9921af94fb69c85a650b05b0eeb4d56623af35f5d71d635b7ba5e2508c02246a"
  license "LGPL-3.0-only"

  bottle do
    root_url "file://#{Dir.home}/FreeFem-bottles"
    sha256 arm64_tahoe: "ab5c75e212d4b3cdaa04fd1c7a502389a15da271bb53e97159f3012ec89543ab"
  end

  depends_on "autoconf" => :build
  depends_on "automake" => :build
  depends_on "cmake" => :build
  depends_on "fftw"
  depends_on "gcc" # libgfortran, libquadmath
  depends_on "gsl"
  depends_on "hdf5"
  depends_on "hwloc"
  depends_on "libevent"
  depends_on "open-mpi"
  depends_on "pmix"

  def install
    gfortran = formula_opt_bin("gcc")/"gfortran"
    gcc      = formula_opt_bin("gcc")/"gcc"
    gcclib   = formula_opt_lib("gcc")/"gcc/current"

    # ── Source patches ─────────────────────────────────────────────
    superlu = "3rdparty/superlu/superlu-sources/SRC"

    # SuperLU: fix empty () forward declarations (errors in Clang 21 / GCC 16 -std=gnu23)
    inreplace "#{superlu}/sgstrs.c",      "void sprint_soln();",         "void sprint_soln(int, int, float *);"
    inreplace "#{superlu}/dgstrs.c",      "void dprint_soln();",         "void dprint_soln(int, int, double *);"
    inreplace "#{superlu}/cgstrs.c",      "void cprint_soln();",         "void cprint_soln(int, int, complex *);"
    inreplace "#{superlu}/zgstrs.c",      "void zprint_soln();",         "void zprint_soln(int, int, doublecomplex *);"
    inreplace "#{superlu}/spanel_bmod.c", "extern void scheck_tempv();", "extern void scheck_tempv(int, float *);"
    inreplace "#{superlu}/cpanel_bmod.c", "extern void ccheck_tempv();", "extern void ccheck_tempv(int, complex *);"
    inreplace "#{superlu}/dpanel_bmod.c", "extern void dcheck_tempv();", "extern void dcheck_tempv(int, double *);"
    inreplace "#{superlu}/zpanel_bmod.c", "extern void zcheck_tempv();", "extern void zcheck_tempv(int, doublecomplex *);"

    %w[s d c z].each do |p|
      path_triple = "#{superlu}/#{p}readtriple.c"
      path_mm     = "#{superlu}/#{p}readMM.c"
      inreplace path_triple, "FILE *fp, *fopen();", "FILE *fp;" if File.exist?(path_triple)
      inreplace path_mm,     "FILE *fp, *fopen();", "FILE *fp;" if File.exist?(path_mm)
    end

    # SuperLU *myblas2.c: convert K&R-style function definitions to ANSI C
    {
      "smyblas2.c" => { type: "float",         matvec: "float *M, float *vec, float *Mxvec" },
      "dmyblas2.c" => { type: "double",        matvec: "double *M, double *vec, double *Mxvec" },
      "cmyblas2.c" => { type: "complex",       matvec: "complex *M, complex *vec, complex *Mxvec" },
      "zmyblas2.c" => { type: "doublecomplex", matvec: "doublecomplex *M, doublecomplex *vec, doublecomplex *Mxvec" },
    }.each do |fname, info|
      path = "#{superlu}/#{fname}"
      pfx  = fname[0]
      t    = info[:type]
      content = File.read(path)
      content.gsub!(
        /void\s*\n#{pfx}usolve\s*\([^)]*\)\s*\nint ldm;.*?int ncol;.*?#{t} \*M;.*?#{t} \*rhs;\s*\n/m,
        "void\n#{pfx}usolve (int ldm, int ncol, #{t} *M, #{t} *rhs)\n",
      )
      content.gsub!(
        /void #{pfx}matvec\s*\([^)]*\)\s*\n+int ldm;.*?int nrow;.*?int ncol;.*?#{t} \*M;.*?#{t} \*vec;.*?#{t} \*Mxvec;\s*\n/m,
        "void #{pfx}matvec (int ldm, int nrow, int ncol, #{info[:matvec]})\n",
      )
      File.write(path, content)
    end

    # Scotch: force -std=gnu11 (GCC 16 defaults to C23, which breaks Scotch's function-pointer tables)
    inreplace "3rdparty/scotch/Makefile-scotch.inc" do |s|
      s.gsub!(/^CCS\s*=.*$/, "CCS = #{gcc} -std=gnu11")
      s.gsub!(/^CCD\s*=.*$/, "CCD = #{gcc} -std=gnu11")
    end

    # ScaLAPACK: K&R missing type for gcontext parameter
    inreplace "3rdparty/scalapack/scalapack-2.1.0/REDIST/SRC/pgemraux.c",
      "  int   i, j, m, n, p, q;",
      "  int   i, j, m, n, p, q, gcontext;"

    # ── Configure ─────────────────────────────────────────────────
    system "tar", "zxf", "AutoGeneratedFile.tar.gz"

    # Keep -std flag out of CC so cmake sub-builds see a plain compiler path
    ENV["CC"]     = gcc.to_s
    ENV["CXX"]    = formula_opt_bin("gcc")/"g++"
    ENV["FC"]     = gfortran.to_s
    ENV["F77"]    = gfortran.to_s
    ENV["CFLAGS"] = "-std=gnu11 #{ENV["CFLAGS"]}"

    system "./configure",
      "--prefix=#{prefix}",
      "--enable-download",
      "--enable-optim",
      "--enable-m64",
      "--enable-maintainer-mode",
      "F77=#{gfortran}",
      "FC=#{gfortran}"

    cd "3rdparty/scotch" do
      system "../../config.status", "--file=Makefile.inc:Makefile-scotch.inc"
      cp "Makefile.inc", "scotch-v6.1.0/src/"
    end

    system "make", "-j#{ENV.make_jobs}"
    system "make", "install"

    # ── Bundle gfortran runtime ────────────────────────────────────
    gnudir = prefix/"gnu"
    gnudir.mkpath

    gfortran_libs = %w[libgfortran.5.dylib libquadmath.0.dylib libgcc_s.1.1.dylib]
    gfortran_libs.each { |lib| cp gcclib/lib, gnudir }
    (gnudir/"libgfortran.dylib").make_symlink "libgfortran.5.dylib"
    (gnudir/"libquadmath.dylib").make_symlink "libquadmath.0.dylib"

    [gnudir/"libgfortran.5.dylib", gnudir/"libquadmath.0.dylib", gnudir/"libgcc_s.1.1.dylib"].each do |f|
      chmod 0644, f
      MachO::Tools.change_dylib_id(f.to_s, "@rpath/#{f.basename}")
      gfortran_libs.each do |dep|
        old = (gcclib/dep).to_s
        begin
          MachO::Tools.change_install_name(f.to_s, old, "@rpath/#{dep}")
        rescue MachO::MachOError
          nil
        end
      end
      system "codesign", "--remove-signature", f.to_s
      system "codesign", "-s", "-", f.to_s
    end

    Dir["#{bin}/*", "#{lib}/**/*.dylib"].each do |f|
      next if File.symlink?(f)
      next unless File.file?(f)

      changed = false
      gfortran_libs.each do |dep|
        old = (gcclib/dep).to_s
        next unless `otool -L #{f}`.include?(old)

        MachO::Tools.change_install_name(f, old, "@rpath/#{dep}")
        changed = true
      end
      next unless changed

      macho = MachO.open(f)
      macho.add_rpath(gnudir.to_s)
      macho.save
      system "codesign", "--remove-signature", f
      system "codesign", "-s", "-", f
    end

    # ── Bundle MPI runtime (libmpi + transitive deps) ─────────────
    # open-mpi links to pmix, hwloc, libevent — bundle them all into
    # extlib/ so the install is self-contained (no Homebrew required).
    extlib = prefix/"extlib"
    extlib.mkpath

    ompi_lib     = formula_opt_lib("open-mpi")
    pmix_lib     = formula_opt_lib("pmix")
    hwloc_lib    = formula_opt_lib("hwloc")
    libevent_lib = formula_opt_lib("libevent")

    mpi_bundles = {
      ompi_lib     => %w[libmpi.40.dylib libmpi_mpifh.40.dylib libmpi_usempi_ignore_tkr.40.dylib libmpi_usempif08.40.dylib libopen-pal.80.dylib],
      pmix_lib     => %w[libpmix.2.dylib],
      hwloc_lib    => %w[libhwloc.15.dylib],
      libevent_lib => %w[libevent_core-2.1.7.dylib libevent_pthreads-2.1.7.dylib],
    }

    all_bundled = mpi_bundles.values.flatten
    mpi_bundles.each do |src_lib, libs|
      libs.each do |lib|
        src = src_lib/lib
        next unless src.exist?

        cp src, extlib/lib
        MachO::Tools.change_dylib_id((extlib/lib).to_s, "@rpath/#{lib}")
        # Redirect cross-references among bundled libs to use @rpath
        all_bundled.each do |dep|
          MachO.open((extlib/lib).to_s).linked_dylibs.select { |d| d.end_with?(dep) }.each do |old|
            MachO::Tools.change_install_name((extlib/lib).to_s, old, "@rpath/#{dep}")
          rescue MachO::MachOError
            nil
          end
        end
        system "codesign", "--remove-signature", extlib/lib
        system "codesign", "-s", "-", extlib/lib
      end
    end

    # ── macOS app bundle ───────────────────────────────────────────
    # Extract the upstream scaffold (icons, AppleScript resources)
    system "tar", "zxf", "FreeFem++.app.tgz", "-C", prefix.to_s

    app = prefix/"FreeFem++.app"

    # Replace the x86-only AppletStub binary with a native shell script launcher
    (app/"Contents/MacOS/droplet").unlink
    (app/"Contents/MacOS/droplet").write <<~SH
      #!/bin/bash
      ff="#{opt_bin}/FreeFem++"
      cmd=""
      for f in "$@"; do
        dir=$(dirname "$f")
        base=$(basename "$f")
        cmd="${cmd}cd $(printf '%q' "$dir"); $ff $(printf '%q' "$base"); "
      done
      [ -z "$cmd" ] && cmd="$ff; "
      osascript <<OSASCRIPT
      tell application "Terminal"
        activate
        do script "${cmd}exit"
      end tell
      OSASCRIPT
    SH
    chmod "+x", app/"Contents/MacOS/droplet"

    # Update Info.plist: remove deprecated keys, set correct bundle metadata
    (app/"Contents/Info.plist").atomic_write <<~PLIST
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
        "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>CFBundleAllowMixedLocalizations</key><true/>
        <key>CFBundleDevelopmentRegion</key><string>en</string>
        <key>CFBundleDocumentTypes</key>
        <array>
          <dict>
            <key>CFBundleTypeExtensions</key><array><string>edp</string></array>
            <key>CFBundleTypeName</key><string>FreeFEM Script</string>
            <key>CFBundleTypeRole</key><string>Editor</string>
          </dict>
        </array>
        <key>CFBundleExecutable</key><string>droplet</string>
        <key>CFBundleIconFile</key><string>FreeFem++</string>
        <key>CFBundleIdentifier</key><string>org.freefem.FreeFem</string>
        <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
        <key>CFBundleName</key><string>FreeFem++</string>
        <key>CFBundleDisplayName</key><string>FreeFem++</string>
        <key>CFBundlePackageType</key><string>APPL</string>
        <key>CFBundleShortVersionString</key><string>#{version}</string>
        <key>CFBundleVersion</key><string>#{version}</string>
        <key>LSMinimumSystemVersion</key><string>12.0</string>
      </dict>
      </plist>
    PLIST

    # Write the app installer helper script
    (bin/"freefem-install-app").write <<~SH
      #!/bin/bash
      # Installs FreeFem++.app into /Applications (or a custom destination).
      # Usage: freefem-install-app [destination]   default: /Applications
      set -e
      SELF="$(python3 -c "import os,sys; print(os.path.realpath(sys.argv[1]))" "$0")"
      PREFIX="$(dirname "$(dirname "$SELF")")"
      APP="$PREFIX/FreeFem++.app"
      [ -d "$APP" ] || { echo "Error: FreeFem++.app not found at $APP" >&2; exit 1; }
      DEST="${1:-/Applications}"
      mkdir -p "$DEST"
      rm -rf "$DEST/FreeFem++.app"
      cp -r "$APP" "$DEST/"
      chmod -R a+rX "$DEST/FreeFem++.app"
      echo "FreeFem++.app installed in $DEST"
      echo "You can now drag .edp files onto it to run FreeFEM++."
    SH
    chmod "+x", bin/"freefem-install-app"
  end

  def caveats
    <<~EOS
      FreeFEM++ #{version} has been installed.

      CLI usage:
        FreeFem++ script.edp
        FreeFem++-mpi -np 4 script.edp

      To install FreeFem++.app so you can drag .edp files onto it, run:
        freefem-install-app            # installs to /Applications (system-wide)
        freefem-install-app ~/Applications  # current user only

      Plugins:
        #{opt_prefix}/lib/ff++/#{version}/lib/
      Gfortran runtime:
        #{opt_prefix}/gnu/
    EOS
  end

  test do
    (testpath/"laplace.edp").write <<~EDP
      load "medit"
      mesh Th = square(10, 10);
      fespace Vh(Th, P1);
      Vh u, v;
      problem Laplace(u, v) =
        int2d(Th)(dx(u)*dx(v) + dy(u)*dy(v))
        - int2d(Th)(1*v)
        + on(1,2,3,4, u=0);
      Laplace;
      cout << "u max = " << u[].max << endl;
    EDP
    system bin/"FreeFem++", "-nw", "laplace.edp"
  end
end
